# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170917_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tg_notify_alerts',
            field=models.BooleanField(default=False, verbose_name='Уведомлять об инцидентах через Telegram'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tg_notify_events',
            field=models.BooleanField(default=False, verbose_name='Уведомлять о событиях через Telegram'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tg_username',
            field=models.CharField(blank=True, max_length=128, verbose_name='Логин в Telegram'),
        ),
    ]
