# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True, verbose_name='Время возникновения')),
                ('checked', models.BooleanField(db_index=True, default=False, verbose_name='Отработано')),
                ('checked_message', models.CharField(blank=True, max_length=512, verbose_name='Пояснительное сообщение')),
            ],
            options={
                'verbose_name': 'Тревога',
                'verbose_name_plural': 'Тревоги',
            },
        ),
        migrations.CreateModel(
            name='AlertType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('level', models.SmallIntegerField(choices=[(0, 'низкий'), (1, 'средний'), (2, 'высокий')], default=0, verbose_name='Уровень тревоги')),
            ],
            options={
                'verbose_name': 'Тип тревоги',
                'verbose_name_plural': 'Типы тревог',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('ipv4', models.CharField(db_index=True, max_length=15, verbose_name='IP адрес')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Актив',
                'verbose_name_plural': 'Активы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AssetUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Имя')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Пользователь актива',
                'verbose_name_plural': 'Пользователи активов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('image', models.ImageField(null=True, upload_to='os/%Y-%m-%d', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Операционная система',
                'verbose_name_plural': 'Операционные системы',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='asset.OperatingSystem', verbose_name='Операционная система'),
        ),
        migrations.AddField(
            model_name='asset',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='asset.AssetUser', verbose_name='Пользователь актива'),
        ),
        migrations.AddField(
            model_name='alert',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='asset.Asset', verbose_name='Актив'),
        ),
        migrations.AddField(
            model_name='alert',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='asset.AlertType', verbose_name='Тип тревоги'),
        ),
    ]
