# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-10 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Пользователь актива',
                'verbose_name_plural': 'Пользователи активов',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to='asset.AssetUser', verbose_name='Пользователь актива'),
        ),
    ]
