# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'verbose_name': 'Инцидент', 'verbose_name_plural': 'Инциденты'},
        ),
        migrations.AlterModelOptions(
            name='alerttype',
            options={'verbose_name': 'Тип инцидента', 'verbose_name_plural': 'Типы инцидентов'},
        ),
        migrations.AlterField(
            model_name='alert',
            name='time',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время возникновения'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='asset.AlertType', verbose_name='Тип инцидента'),
        ),
        migrations.AlterField(
            model_name='alerttype',
            name='level',
            field=models.SmallIntegerField(choices=[(0, 'низкий'), (1, 'средний'), (2, 'высокий')], default=0, verbose_name='Уровень важности'),
        ),
    ]
