# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_data',
        ),
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.AddField(
            model_name='event',
            name='data',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='dt',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='source',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
